name: lpe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - postgresql
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - pip:
    - click>=8.1.0
    - rich>=13.0.0
    - psycopg2-binary>=2.9.0
    - sqlalchemy>=2.0.0
    - pgvector>=0.2.0
    - python-dotenv>=1.0.0
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0
    - sentence-transformers>=2.2.0
    - pytest>=7.3.0
    - black>=23.3.0
    - flake8>=6.0.0